server:
  port: 9000

spring:
  application:
    name: authentication
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:${server.port}
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${server.port}

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/taskmanager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate   # IMPORTANT: let Flyway manage schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false
        cache:
          use_second_level_cache: false
          use_query_cache: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO